# Generated by Django 6.0.3 on 2026-03-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("esc", "0001_initial"),
        ("lifts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replacement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата замены")),
                ("info_replacement", models.TextField(verbose_name="Что стоит заменить")),
                ("resolved", models.BooleanField(default=False, verbose_name="Заменено?")),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_building",
                        to="buildings.building",
                        verbose_name="Здание",
                    ),
                ),
                (
                    "elevator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_elevator",
                        to="lifts.elevator",
                        verbose_name="Лифт",
                    ),
                ),
                (
                    "esc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_esc",
                        to="esc.esc",
                        verbose_name="Эскалатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замена",
                "verbose_name_plural": "Замены",
            },
        ),
    ]
