# Generated by Django 6.0.3 on 2026-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("esc", "0001_initial"),
        ("lifts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "address",
                    models.CharField(
                        choices=[
                            ("D36", "д. 36"),
                            ("D36STR9", "д. 36 стр. 9"),
                            ("D36STR10", "д. 36 стр. 10"),
                            ("D36STR11", "д. 36 стр. 11"),
                            ("D36STR28", "д. 36 стр. 28"),
                            ("D36STR41", "д. 36 стр. 41"),
                            ("MSTK", "МСТК"),
                        ],
                        default="D36",
                        help_text="Выбери адрес",
                        max_length=14,
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "elevators",
                    models.ManyToManyField(related_name="buildings_lift", to="lifts.elevator", verbose_name="Лифты"),
                ),
                (
                    "escs",
                    models.ManyToManyField(related_name="buildings_esc", to="esc.esc", verbose_name="Эскалаторы"),
                ),
            ],
            options={
                "verbose_name": "Здание",
                "verbose_name_plural": "Здания",
            },
        ),
    ]
